AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'serverless-data-pipelines

  Sample SAM Template for serverless-data-pipelines

  '
Globals:
  Function:
    Timeout: 100
Parameters:
  MainDataBucket:
    Type: String
    Default: big-data-class1
  MainDataBucketArn:
    Type: String
    Default: arn:aws:s3:::big-data-class1
Resources:
  LambaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: LambaExecutionPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:ListBucket
            Resource:
              Ref: MainDataBucketArn
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:GetObject
            - s3:ListBucket
            Resource:
              Fn::Join:
              - /
              - - Ref: MainDataBucketArn
                - '*'
          - Effect: Allow
            Action:
            - cloudwatch:PutMetricData
            - logs:CreateLogStream
            - logs:PutLogEvents
            - logs:CreateLogGroup
            - logs:DescribeLogStreams
            Resource: '*'
  EMRFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: EMRFunction
      CodeUri: s3://big-data-class1/fea49c04ae6c7a5dca4ee4f00a50e6ef
      Handler: app.lambda_handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - LambaExecutionRole
        - Arn
      MemorySize: 1024
  GetDataFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetDataFunction
      CodeUri: s3://big-data-class1/bc5a87935ef25220bfa9bf2422c41a9d
      Handler: app.lambda_handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - LambaExecutionRole
        - Arn
      MemorySize: 1024
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
Outputs:
  EMRFunction:
    Description: None
    Value:
      Fn::GetAtt:
      - EMRFunction
      - Arn
  GetDataFunction:
    Description: None
    Value:
      Fn::GetAtt:
      - GetDataFunction
      - Arn
