AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-data-pipelines

  Sample SAM Template for serverless-data-pipelines

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 100

Resources:
  EMRFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: EMRFunction
      CodeUri: emr-1/
      Handler: app.lambda_handler
      Runtime: python3.7
      # Layers:
      # - !Ref DataProcessingLayer


  # note, role requires s3 access
  GetDataFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: GetDataFunction
      CodeUri: get-data/
      Handler: app.lambda_handler
      Runtime: python3.7
      # Layers: -- Can't build this without sam
      # - !Ref DataProcessingLayer
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)




  # DataProcessingLib:
  #   Type: AWS::Serverless::Function
  #   Properties:
  #     CodeUri: ./src/layers/dataProcessingLib/
  #     Handler: data_processing_lib.lambda_handler
  #     Runtime: python3.7


  # DataProcessingLayer:
  #   Type: AWS::Serverless::LayerVersion
  #   DependsOn: DataProcessingLib
  #   Properties:
  #     Description: Lambda layer for writing additional functions for data processing
  #     LayerName: DataProcessingLib
  #     ContentUri: ./.aws-sam/build/DataProcessingLib
  #     CompatibleRuntimes: 
  #       - python3.7
  #     RetentionPolicy: Delete

Outputs:
  

  EMRFunction:
    Description: "None"
    Value: !GetAtt EMRFunction.Arn
  EMRFunctionIamRole:
    Description: "None"
    Value: !GetAtt EMRFunctionRole.Arn


  GetDataFunction:
    Description: "None"
    Value: !GetAtt GetDataFunction.Arn
  GetDataFunctionIamRole:
    Description: "None"
    Value: !GetAtt GetDataFunctionRole.Arn


  # DataProcessingLib:
  #   Description: "Processing Layer"
  #   Value: !GetAtt DataProcessingLib.Arn